-- ============================================================
-- FitGO — Migration 018: Comprehensive Schema Fixes
-- Generated by project audit (2026-05-14)
-- ============================================================

-- ─── 1. Fix coach_sessions.coach_type to include 'doctor' ─────
-- The DoctorScreen.tsx creates sessions with coach_type='doctor',
-- but the original CHECK constraint only allows 'nutritionist' and 'trainer'.
ALTER TABLE public.coach_sessions DROP CONSTRAINT IF EXISTS coach_sessions_coach_type_check;
ALTER TABLE public.coach_sessions ADD CONSTRAINT coach_sessions_coach_type_check
  CHECK (coach_type IN ('nutritionist', 'trainer', 'doctor'));

-- ─── 2. Relax meal_plan_items.meal constraint ─────────────────
-- The original constraint doesn't allow extra snack slots (snack2, snack3, etc.)
-- that the app generates via the "Add Snack" feature.
ALTER TABLE public.meal_plan_items DROP CONSTRAINT IF EXISTS meal_plan_items_meal_check;
ALTER TABLE public.meal_plan_items ADD CONSTRAINT meal_plan_items_meal_check
  CHECK (meal ~ '^(breakfast|lunch|dinner|snack\d*)$');

-- ─── 3. Add missing available_foods column to users ───────────
-- The app stores user's preferred foods in the profile, but the column
-- was never added to the schema.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS available_foods TEXT[] DEFAULT '{}';

-- ─── 4. Add missing starting_weight column to users ───────────
-- Referenced in authStore.ts fetchProfile but may not exist.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS starting_weight NUMERIC(5,2);

-- ─── 5. Add index on coach_conversations.session_id ───────────
-- Queries frequently filter by session_id; this improves join/filter performance.
CREATE INDEX IF NOT EXISTS idx_coach_conversations_session
  ON public.coach_conversations (session_id);

-- ─── 6. Fix RLS policy conflict on users table ────────────────
-- The original 'users_own' policy from migration 001 applies to ALL operations
-- (SELECT, INSERT, UPDATE, DELETE) because it lacks a FOR clause.
-- This conflicts with the restricted 'users_update_own' policy from migration 008
-- that protects is_pro and role from self-modification.
-- Solution: Drop the overly permissive policy and create explicit per-operation policies.

-- Drop the original overly permissive policy
DROP POLICY IF EXISTS "users_own" ON public.users;

-- SELECT: Users can read their own data (admins handled by 'admins_read_all_users')
CREATE POLICY "users_select_own" ON public.users
  FOR SELECT
  USING (auth.uid() = id);

-- INSERT: Users can insert their own profile row during registration
CREATE POLICY "users_insert_own" ON public.users
  FOR INSERT
  WITH CHECK (auth.uid() = id);

-- DELETE: Users can delete their own account
CREATE POLICY "users_delete_own" ON public.users
  FOR DELETE
  USING (auth.uid() = id);

-- Note: UPDATE is already handled by 'users_update_own' in migration 008,
-- which prevents self-modification of is_pro and role.

-- ─── 7. Add missing RLS policies for recipes table ────────────
-- Currently only has a SELECT policy. Users need INSERT/UPDATE/DELETE for their own recipes.
CREATE POLICY "recipes_insert_own" ON public.recipes
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "recipes_update_own" ON public.recipes
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "recipes_delete_own" ON public.recipes
  FOR DELETE
  USING (auth.uid() = user_id);

-- ─── 8. Add RLS policies for meal_plan_items ──────────────────
-- INSERT/UPDATE/DELETE need explicit policies for the app to manage plan items.
DROP POLICY IF EXISTS "plan_items_insert_own" ON public.meal_plan_items;
CREATE POLICY "plan_items_insert_own" ON public.meal_plan_items
  FOR INSERT
  WITH CHECK (
    plan_id IN (SELECT id FROM public.meal_plans WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "plan_items_update_own" ON public.meal_plan_items;
CREATE POLICY "plan_items_update_own" ON public.meal_plan_items
  FOR UPDATE
  USING (
    plan_id IN (SELECT id FROM public.meal_plans WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "plan_items_delete_own" ON public.meal_plan_items;
CREATE POLICY "plan_items_delete_own" ON public.meal_plan_items
  FOR DELETE
  USING (
    plan_id IN (SELECT id FROM public.meal_plans WHERE user_id = auth.uid())
  );

-- ─── 9. Add full RLS policies for food_logs ──────────────────
-- Ensure INSERT, UPDATE, DELETE are all explicitly covered.
DROP POLICY IF EXISTS "food_logs_insert_own" ON public.food_logs;
CREATE POLICY "food_logs_insert_own" ON public.food_logs
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "food_logs_update_own" ON public.food_logs;
CREATE POLICY "food_logs_update_own" ON public.food_logs
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "food_logs_delete_own" ON public.food_logs;
CREATE POLICY "food_logs_delete_own" ON public.food_logs
  FOR DELETE
  USING (auth.uid() = user_id);

-- ─── 10. Add full RLS policies for body_measurements ──────────
DROP POLICY IF EXISTS "body_meas_insert_own" ON public.body_measurements;
CREATE POLICY "body_meas_insert_own" ON public.body_measurements
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "body_meas_update_own" ON public.body_measurements;
CREATE POLICY "body_meas_update_own" ON public.body_measurements
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "body_meas_delete_own" ON public.body_measurements;
CREATE POLICY "body_meas_delete_own" ON public.body_measurements
  FOR DELETE
  USING (auth.uid() = user_id);
